apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tcz8301qq-go
  janus-idp.io/tekton: tcz8301qq-go
  backstage.io/kubernetes-id: tcz8301qq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tcz8301qq-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
